services:
  backend:
    image: dpinfosystem/marinellp-backend:latest
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: marinellp-backend
    restart: always
    ports:
      - "8002:8002"
    env_file:
      - apps/backend/.env
    environment:
      - PORT=8002

  frontend:
    image: dpinfosystem/marinellp-frontend:latest
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: marinellp-frontend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - apps/frontend/.env.local
    environment:
      - PORT=3000
    depends_on:
      - backend
